#!/bin/bash

#SBATCH --job-name=KIRC_ruche
#SBATCH --output=%x.o%j
#SBATCH --time=03:00:00
#SBATCH --array=0-14
#SBATCH --ntasks=40
#SBATCH --partition=cpu_med                                                                                                                                                                                 


[ ! -d output ] && mkdir output

module  load anaconda3/2020.02/gcc-9.2.0
source activate keras

## Go to the directory where the job has been submitted
#cd $PBS_O_WORKDIR

# Execution
python NNsurv.py "data/simuZ_vf_KIRC.csv" "data/surv_time_vf_KIRC.csv" "data/right_cens_vf_KIRC.csv" $SLURM_ARRAY_TASK_ID
